sudo: required

services:
    - docker


before_install: ./ci/run_before_install.sh

jobs:
    include:
        - stage: unittest
          script: ./ci/run_unittest.sh
        - stage: applications
          script: ./ci/run_applications.sh
        - stage: notebooks
          script: ./ci/run_notebooks.sh 


