sudo: required

language: python

services:
    - docker

before_install:
    - docker pull quay.io/fenicsproject/stable:2016.1.0
    
install:
    
script:
    - ls
    - docker run --rm -v $(pwd):/home/fenics/hippylib -w /home/fenics/hippylib quay.io/fenicsproject/stable:2016.1.0 "dolfin-version"
    - docker run --rm -v $(pwd):/home/fenics/hippylib -w /home/fenics/hippylib/applications/poisson quay.io/fenicsproject/stable:2016.1.0 "mpirun -n 4 python model_subsurf.py"
