sudo: required

language: python

services:
    - docker

before_install:
    - docker pull quay.io/fenicsproject/stable:2016.1.0
    
install:
    
script:
    - ls
    - docker run --name hip -d quay.io/fenicsproject/stable:2016.1.0 /bin/bash -c "dolfin-version"
    - docker logs hip
