sudo: required

language: python

services:
    - docker

before_install:
    - docker pull quay.io/fenicsproject/stable:2016.1.0.r4
    - docker run -d quay.io/fenicsproject/stable:2016.1.0.r4 /bin/sh -c "dolfin-version"
    - docker ps -a
    
install:
    
script:
    - ls
    - docker run -d quay.io/fenicsproject/stable:2016.1.0.r4 /bin/sh -c "dolfin-version"
